-- Rental billing schema + automation for Supabase/PostgreSQL
-- Run in Supabase SQL editor.

begin;

create table if not exists public.rooms (
  room_id bigint generated by default as identity primary key,
  room_no text not null unique,
  monthly_rent numeric(12, 2) not null check (monthly_rent >= 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

-- Assumes public.users(user_id) already exists.
create table if not exists public.tenants (
  tenant_id bigint generated by default as identity primary key,
  user_id uuid not null,
  room_id bigint not null references public.rooms(room_id) on update cascade on delete restrict,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint tenants_user_id_unique unique (user_id),
  constraint tenants_user_id_fkey foreign key (user_id) references public.users(user_id) on update cascade on delete cascade
);

create table if not exists public.billing_ledger (
  billing_id bigint generated by default as identity primary key,
  tenant_id bigint not null references public.tenants(tenant_id) on update cascade on delete cascade,
  billing_month smallint not null check (billing_month between 1 and 12),
  billing_year integer not null check (billing_year >= 2000),
  due_date date not null,
  amount_due numeric(12, 2) not null check (amount_due >= 0),
  amount_paid numeric(12, 2) not null default 0 check (amount_paid >= 0),
  balance numeric(12, 2) not null check (balance >= 0),
  status text not null default 'Billing' check (status in ('Billing', 'Partially Paid', 'Paid', 'Overdue')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint billing_ledger_tenant_month_year_unique unique (tenant_id, billing_month, billing_year),
  constraint billing_ledger_billing_tenant_unique unique (billing_id, tenant_id)
);

create table if not exists public.payments (
  payment_id bigint generated by default as identity primary key,
  billing_id bigint not null,
  tenant_id bigint not null,
  payment_date date not null default current_date,
  amount_paid numeric(12, 2) not null check (amount_paid > 0),
  payment_method text not null,
  receipt_proof text,
  status text not null default 'pending' check (lower(status) in ('pending', 'paid', 'partially paid', 'rejected')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint payments_tenant_id_fkey foreign key (tenant_id) references public.tenants(tenant_id) on update cascade on delete cascade,
  constraint payments_billing_tenant_fkey foreign key (billing_id, tenant_id)
    references public.billing_ledger (billing_id, tenant_id)
    on update cascade
    on delete cascade
);

create index if not exists idx_billing_ledger_tenant_id on public.billing_ledger(tenant_id);
create index if not exists idx_billing_ledger_due_status on public.billing_ledger(due_date, status);
create index if not exists idx_payments_billing_id on public.payments(billing_id);
create index if not exists idx_payments_tenant_id on public.payments(tenant_id);
create index if not exists idx_payments_status on public.payments(status);
create index if not exists idx_payments_payment_date on public.payments(payment_date desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

drop trigger if exists rooms_set_updated_at on public.rooms;
create trigger rooms_set_updated_at
before update on public.rooms
for each row
execute function public.set_updated_at();

drop trigger if exists tenants_set_updated_at on public.tenants;
create trigger tenants_set_updated_at
before update on public.tenants
for each row
execute function public.set_updated_at();

drop trigger if exists billing_ledger_set_updated_at on public.billing_ledger;
create trigger billing_ledger_set_updated_at
before update on public.billing_ledger
for each row
execute function public.set_updated_at();

drop trigger if exists payments_set_updated_at on public.payments;
create trigger payments_set_updated_at
before update on public.payments
for each row
execute function public.set_updated_at();

-- Creates one billing row per tenant per month using current room rent.
create or replace function public.create_monthly_billing_entries(
  p_billing_month smallint,
  p_billing_year integer,
  p_due_date date default null
)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  v_due_date date;
  v_inserted_rows integer := 0;
begin
  if p_billing_month < 1 or p_billing_month > 12 then
    raise exception 'billing month must be between 1 and 12';
  end if;

  if p_billing_year < 2000 then
    raise exception 'billing year must be >= 2000';
  end if;

  v_due_date := coalesce(
    p_due_date,
    (make_date(p_billing_year, p_billing_month, 1) + interval '1 month' - interval '1 day')::date
  );

  insert into public.billing_ledger (
    tenant_id,
    billing_month,
    billing_year,
    due_date,
    amount_due,
    amount_paid,
    balance,
    status
  )
  select
    t.tenant_id,
    p_billing_month,
    p_billing_year,
    v_due_date,
    r.monthly_rent,
    0,
    r.monthly_rent,
    'Billing'
  from public.tenants t
  join public.rooms r on r.room_id = t.room_id
  on conflict (tenant_id, billing_month, billing_year) do nothing;

  get diagnostics v_inserted_rows = row_count;
  return v_inserted_rows;
end;
$$;

-- Recomputes billing totals and ledger status from approved payments.
create or replace function public.recalculate_billing_ledger(p_billing_id bigint)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_due_date date;
  v_amount_due numeric(12, 2);
  v_total_paid numeric(12, 2);
  v_balance numeric(12, 2);
  v_status text;
begin
  select due_date, amount_due
    into v_due_date, v_amount_due
  from public.billing_ledger
  where billing_id = p_billing_id
  for update;

  if not found then
    raise exception 'billing ledger not found for billing_id=%', p_billing_id;
  end if;

  select coalesce(sum(amount_paid), 0)
    into v_total_paid
  from public.payments
  where billing_id = p_billing_id
    and lower(status) in ('paid', 'partially paid');

  v_balance := greatest(v_amount_due - v_total_paid, 0);

  if v_balance = 0 then
    v_status := 'Paid';
  elsif v_balance > 0 and v_total_paid > 0 then
    v_status := 'Partially Paid';
  elsif current_date > v_due_date and v_balance > 0 then
    v_status := 'Overdue';
  else
    v_status := 'Billing';
  end if;

  update public.billing_ledger
  set amount_paid = v_total_paid,
      balance = v_balance,
      status = v_status,
      updated_at = timezone('utc', now())
  where billing_id = p_billing_id;
end;
$$;

create or replace function public.trg_recalculate_billing_ledger_from_payments()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'DELETE' then
    perform public.recalculate_billing_ledger(old.billing_id);
    return old;
  end if;

  perform public.recalculate_billing_ledger(new.billing_id);

  if tg_op = 'UPDATE' and old.billing_id is distinct from new.billing_id then
    perform public.recalculate_billing_ledger(old.billing_id);
  end if;

  return new;
end;
$$;

drop trigger if exists payments_recalculate_billing_ledger on public.payments;
create trigger payments_recalculate_billing_ledger
after insert or update of amount_paid, status, billing_id or delete
on public.payments
for each row
execute function public.trg_recalculate_billing_ledger_from_payments();

commit;
